-- Phase 2: Notifications
CREATE TABLE IF NOT EXISTS notification (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id     BIGINT,
    library_id  BIGINT,
    type        VARCHAR(50),
    channel     VARCHAR(30) DEFAULT 'IN_APP',
    title       VARCHAR(500) NOT NULL,
    message     TEXT,
    is_read     BOOLEAN DEFAULT FALSE,
    is_archived BOOLEAN DEFAULT FALSE,
    action_url  VARCHAR(500),
    created_at  DATETIME,
    read_at     DATETIME,
    INDEX idx_notif_user    (user_id),
    INDEX idx_notif_library (library_id),
    INDEX idx_notif_read    (is_read),
    FOREIGN KEY (user_id)    REFERENCES user(id)    ON DELETE CASCADE,
    FOREIGN KEY (library_id) REFERENCES library(id) ON DELETE CASCADE
);

-- Phase 6: Audit Log
CREATE TABLE IF NOT EXISTS audit_log (
    id                      BIGINT AUTO_INCREMENT PRIMARY KEY,
    performed_by_user_id    BIGINT,
    library_id              BIGINT,
    action                  VARCHAR(50),
    entity_type             VARCHAR(100),
    entity_id               VARCHAR(100),
    description             VARCHAR(500),
    old_value               TEXT,
    new_value               TEXT,
    ip_address              VARCHAR(100),
    user_agent              VARCHAR(500),
    performed_at            DATETIME NOT NULL,
    INDEX idx_audit_library (library_id),
    INDEX idx_audit_user    (performed_by_user_id),
    INDEX idx_audit_ts      (performed_at),
    FOREIGN KEY (performed_by_user_id) REFERENCES user(id) ON DELETE SET NULL,
    FOREIGN KEY (library_id)           REFERENCES library(id) ON DELETE CASCADE
);

-- Phase 11: Support Tickets
CREATE TABLE IF NOT EXISTS support_ticket (
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    library_id          BIGINT NOT NULL,
    created_by_user_id  BIGINT,
    subject             VARCHAR(500),
    description         TEXT,
    status              VARCHAR(30) NOT NULL DEFAULT 'OPEN',
    priority            VARCHAR(20) DEFAULT 'MEDIUM',
    created_at          DATETIME,
    updated_at          DATETIME,
    resolved_at         DATETIME,
    INDEX idx_ticket_library (library_id),
    INDEX idx_ticket_status  (status),
    FOREIGN KEY (library_id)         REFERENCES library(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by_user_id) REFERENCES user(id)    ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS ticket_reply (
    id                  BIGINT AUTO_INCREMENT PRIMARY KEY,
    ticket_id           BIGINT NOT NULL,
    replied_by_user_id  BIGINT,
    message             TEXT NOT NULL,
    is_admin_reply      BOOLEAN DEFAULT FALSE,
    created_at          DATETIME,
    FOREIGN KEY (ticket_id)          REFERENCES support_ticket(id) ON DELETE CASCADE,
    FOREIGN KEY (replied_by_user_id) REFERENCES user(id)           ON DELETE SET NULL
);

-- Phase 12: Announcements
CREATE TABLE IF NOT EXISTS announcement (
    id                BIGINT AUTO_INCREMENT PRIMARY KEY,
    title             VARCHAR(500),
    content           TEXT,
    type              VARCHAR(40),
    target_library_id BIGINT,
    active            BOOLEAN DEFAULT TRUE,
    created_at        DATETIME,
    expires_at        DATETIME,
    FOREIGN KEY (target_library_id) REFERENCES library(id) ON DELETE SET NULL
);

-- Phase 9: White-label fields (add if not exist)
ALTER TABLE library ADD COLUMN IF NOT EXISTS logo_url         VARCHAR(500);
ALTER TABLE library ADD COLUMN IF NOT EXISTS primary_color    VARCHAR(20);
ALTER TABLE library ADD COLUMN IF NOT EXISTS secondary_color  VARCHAR(20);
ALTER TABLE library ADD COLUMN IF NOT EXISTS custom_footer    VARCHAR(500);
ALTER TABLE library ADD COLUMN IF NOT EXISTS timezone         VARCHAR(100);

-- Password Reset Token
CREATE TABLE IF NOT EXISTS password_reset_token (
    id          BIGINT AUTO_INCREMENT PRIMARY KEY,
    token       VARCHAR(255) NOT NULL UNIQUE,
    user_id     BIGINT NOT NULL,
    expires_at  DATETIME NOT NULL,
    used        BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE,
    INDEX idx_prt_token (token)
);

-- Fee table composite indexes (only if not exist via Hibernate)
-- These are generated by Hibernate from @Table(indexes=...) but listed here for manual runs
-- CREATE INDEX IF NOT EXISTS idx_fee_lib_month_status ON fee(library_id, month_id, fee_status);

-- Student Self-Registration fields
ALTER TABLE student ADD COLUMN IF NOT EXISTS registration_status VARCHAR(30) DEFAULT NULL;
ALTER TABLE student ADD COLUMN IF NOT EXISTS father_name    VARCHAR(200);
ALTER TABLE student ADD COLUMN IF NOT EXISTS address        TEXT;
ALTER TABLE student ADD COLUMN IF NOT EXISTS photo_url      VARCHAR(500);
ALTER TABLE student ADD COLUMN IF NOT EXISTS aadhar_photo_url VARCHAR(500);
ALTER TABLE student ADD COLUMN IF NOT EXISTS approved_at    DATETIME;
ALTER TABLE student ADD COLUMN IF NOT EXISTS rejection_reason VARCHAR(500);

-- Library Self-Registration settings
ALTER TABLE library ADD COLUMN IF NOT EXISTS library_code          VARCHAR(20) UNIQUE;
ALTER TABLE library ADD COLUMN IF NOT EXISTS registration_enabled  BOOLEAN DEFAULT TRUE;
ALTER TABLE library ADD COLUMN IF NOT EXISTS require_admin_approval BOOLEAN DEFAULT TRUE;
