package com.learningJWT.LearningTemplate.Enum;
public enum NotificationType {
    FEE_DUE, FEE_OVERDUE, SEAT_EXPIRY, PLAN_EXPIRY,
    ATTENDANCE_ALERT, PAYMENT_SUBMITTED, PAYMENT_APPROVED,
    PAYMENT_REJECTED, ANNOUNCEMENT, SYSTEM, SUPPORT_REPLY
}
